version: '3.5'

services:
  db:
    image: postgres:15.4
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_DB: 'td_slack_bot_development'
      POSTGRES_USER: 'td_slack_bot'
      POSTGRES_PASSWORD: 'secret'
  web: &rails
    build: .
    command: bundle exec rails server -b 0.0.0.0
    env_file: envvars
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db:
