---
apiVersion: v1
data:
  .dockerconfigjson: {{ (print .Values.app.imagePullCredentional) | b64enc | quote }}
kind: Secret
metadata:
  name: app-{{ .Values.serviceName }}-imagepull-credentional
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
