---
apiVersion: v1
data:
  .dockerconfigjson: {{ (print .Values.app.imagePullCredentials) | b64enc | quote }}
kind: Secret
metadata:
  name: app-{{ .Values.serviceName }}-imagepull-credentials
  namespace: {{ $.Release.Namespace }}
type: kubernetes.io/dockerconfigjson
