---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-{{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $val := .Values.app.secret }}
  {{ $key }}: {{ (print $val) | b64enc | quote }}
{{ end }}
