---
apiVersion: v1
kind: Service
metadata:
  name: app-{{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: app-{{ .Values.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: app-{{ .Values.serviceName }}
  ports:
  - port: 80
    name: http-port-80
    protocol: TCP
    targetPort: 3000
