---
apiVersion: {{ template "deployment.apiVersion" $ }}
kind: Deployment
metadata:
  name: clock-{{ .Values.serviceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: clock-{{ .Values.serviceName }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: clock-{{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: clock-{{ .Values.serviceName }}
        logging: "true"
    spec:
      imagePullSecrets:
        - name: app-{{ .Values.serviceName }}-imagepull-credentials
      containers:
        - name: app-{{ .Values.serviceName }}
          image: "{{ .Values.app.imagePath }}:{{ .Values.serviceVersion }}"
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          env:
            - name: CHECKSUM_CONFIG
              value: {{ (print $.Values.app.config) | sha256sum }}
            - name: CHECKSUM_SECRET
              value: {{ (print $.Values.app.secret) | sha256sum }}
       {{- if .Values.clusterName }}
          envFrom:
            - configMapRef:
                name: "app-{{ .Values.serviceName }}"
            - secretRef:
                name: "{{ .Values.clusterName }}-{{ $.Release.Namespace }}"
       {{- else }}
          envFrom:
            - configMapRef:
                name: app-{{ .Values.serviceName }}
            - secretRef:
                name: app-{{ .Values.serviceName }}
       {{- end }}
          args: ["clockwork", "clock.rb"]
