---
apiVersion: batch/v1
kind: Job
metadata:
  name: app-{{ .Values.serviceName }}-{{ .Release.Revision }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: app-{{ .Values.serviceName }}-imagepull-credentional
      containers:
        - name: app-migration-{{ .Values.serviceName }}
          image: {{ .Values.app.imagePath }}:{{ .Values.serviceVersion }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
          env:
          - name: CHECKSUM_CONFIG
            value: {{ (print $.Values.app.config) | sha256sum }}
          - name: CHECKSUM_SECRET
            value: {{ (print $.Values.app.secret) | sha256sum }}
          envFrom:
          - configMapRef:
              name: app-{{ .Values.serviceName }}
          - secretRef:
              name: app-{{ .Values.serviceName }}
          command:
          - rails
          - db:migrate
