---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-{{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-{{ .Values.serviceName }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres-{{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: postgres-{{ .Values.serviceName }}
    spec:
      containers:
        - name: postgres-{{ .Values.serviceName }}
          image: {{ .Values.postgres.imagePath }}
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          env:
          - name: CHECKSUM_CONFIG
            value: {{ (print $.Values.app.config) | sha256sum }}
          - name: CHECKSUM_SECRET
            value: {{ (print $.Values.app.secret) | sha256sum }}
          envFrom:
          - secretRef:
              name: postgres-{{ .Values.serviceName }}
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: postgres-data-volume
            subPath: data
      volumes:
        - name: postgres-data-volume
          persistentVolumeClaim:
            claimName: postgres-data-pvc-{{ .Values.serviceName }}
